# Generated by Django 4.0.6 on 2023-02-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_item_orderitem_product_remove_order_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
    ]
