# Generated by Django 4.0.6 on 2022-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Category 1'), ('2', 'Category 2'), ('3', 'Category 3'), ('4', 'Category 4')], max_length=20),
        ),
    ]
