# Generated by Django 4.0.6 on 2024-02-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='guest_registered_merged',
            field=models.BooleanField(default=False),
        ),
    ]
