# Generated by Django 4.0.6 on 2024-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customer_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Id'),
        ),
    ]
