# Generated by Django 4.0.6 on 2024-01-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_rename_device_customer_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deviceId',
            field=models.CharField(max_length=200, null=True, verbose_name='Device Id'),
        ),
    ]
