# Generated by Django 4.0.6 on 2024-01-24 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_customer_deviceid_accountinfo_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='deviceId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Id'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='house_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='region_or_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='town',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
