# Generated by Django 4.0.6 on 2024-01-25 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_alter_accountinfo_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='customer',
            field=models.ForeignKey(blank=True, default='guestuser@gmail.com', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
