# Generated by Django 4.0.6 on 2024-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_customer_deviceid_alter_accountinfo_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='deviceId',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Device Id or Full Name'),
        ),
    ]
